### ISSUE TITLE
[Bug]:  apple account wont load

### ISSUE THREAD

**Issue by carlosbaq** [ciderapp/Cider#1407]
### Describe the Bug

well I have cider in 3 pcs now, amazing app. problem is now in my house pc, just suddenly the app kicked my apple acount (happened before), but this time it just wont load even tho its correct. only load songs but can't play them. so when I press anything else asks me again my apple account 

### Steps to Reproduce

1. Open Cider
2. ask me to load my apple account
3. successfully done
4. nothing happened, nothing works
5. ask my apple account again everytime 

### Environment Information

- OS: windows 11 
- App Version and/or Commit ID: 

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by blinkbear** [comment]
I have the same problem.

**Comment by blinkbear** [comment]
The problem has been solved in #1405

**Comment by Shane-Park** [comment]
I had the same problem. I updated to 1.5.6 version and it works now
![image](https://user-images.githubusercontent.com/74809918/188067764-55d32d1c-24c1-4e4b-9774-bd630c242f1f.png)

**Comment by MikhailTNY** [comment]
FYI: I'm using 1.5.6 on Windows 11 and still have this issue.

**Comment by coredev-uk** [comment]
Read into the comments in #1405. Update Cider and the issue should fix.
