### ISSUE TITLE
[Bug]: This error keeps happening everytime i start up cider: "cider is not responding reload the app"

### ISSUE THREAD

**Issue by direrFlood** [ciderapp/Cider#1491]
### Describe the Bug

open windows store cider application on windows 11 22h2. receive this error:"[Bug]: This error keeps happening everytime i start up cider: "cider is not responding reload the app""

### Steps to Reproduce

1.start store app on windows 11 build 22h2
2. receive error

### Environment Information

- OS: w11 22h2 
- Desktop Environment: w11
- App Version:
- Commit ID:

### How did you download the software?

Microsoft Store

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by redromnon** [comment]
I'm getting this error on my Linux machine as well.

### Environment Information
OS: Pop OS 22.04 LTS 
Desktop Environment: Gnome 42.4
App Version:
Commit ID:

### How did you download the software?
Flatpak

**Comment by cryptofyre** [comment]
Fixed, our API had some downtime.

**Comment by jsrdzhk** [comment]
cider version 1.6.0
windows version 22H2 OS build 22621.900
still have this problem on each start,please investigate...
